config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :profiles
  resources :messages
  resources :carpool_passengers do
    member do
      put :approve
      put :decline
    end
  end
  resources :chapters do
    resources :carpools do
      member do
        get :join
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users
      resources :profiles
      resources :messages
      resources :carpool_passengers do
        member do
          put :approve
          put :decline
        end
      end
      resources :chapters do
        resources :carpools do
          member do
            get :join
          end
        end
      end
    end
  end

  get 'author', to: 'resumes#index'

  root to: "main#index"

end

app/views/shared/_card.html.haml
.card.top-10
  .card-body
    %h5.card-title= title
    %p.card-text= content

app/views/shared/_form_errors.html.haml
- if model.errors.any?
  #error_explanation
    %ul
      - model.errors.full_messages.each do |err|
        %li= err

app/views/shared/_javascripts.html.haml
= javascript_include_tag '//code.jquery.com/jquery-3.3.1.slim.min.js', integrity: "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", crossorigin: "anonymous"
= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js', integrity: "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49", crossorigin: "anonymous"
= javascript_include_tag '//stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js', integrity: "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy", crossorigin: "anonymous"
= javascript_include_tag '//maps.googleapis.com/maps/api/js?key=&libraries=places'
= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js'
-# = javascript_include_tag '//maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places'
= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/geocomplete/1.7.0/jquery.geocomplete.min.js'
= javascript_include_tag 'application'

app/views/shared/_oauth_buttons.html.haml
= link_to "Log in with Facebook", '', class: 'form-control btn btn-info facebook-button'

app/views/shared/_stylesheets.html.haml
= stylesheet_link_tag '//fonts.googleapis.com/css?family=Open+Sans|Quicksand'
= stylesheet_link_tag '//stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css', media: 'all', integrity: "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO", crossorigin: "anonymous"
= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css'
= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css'
= stylesheet_link_tag 'application', media: 'all'

app/views/shared/_top_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.top-nav
  = link_to root_path, class: 'navbar-brand' do
    Carpoolers

  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon

  #navbarSupportedContent.collapse.navbar-collapse

    %ul.navbar-nav.mr-auto
      %li.nav-item
        = link_to chapters_path, class: 'nav-link' do
          = t('chapters')
      %li.nav-item
        = link_to new_chapter_path, class: 'nav-link' do
          = t('submit_your_chapter')

    %ul.navbar-nav.justify-content-end
      - if user_signed_in?
        %li.nav-item.dropdown
          = link_to '#', id: 'navbarDropdown', class: 'nav-link dropdown-toggle', role: "button", "aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown" do
            My Account
          .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            %a.dropdown-item{:href => "#"} Action
            %a.dropdown-item{:href => "#"} Another action
            .dropdown-divider
            %a.dropdown-item{:href => "#"} Something else here
        %li.nav-item
          = link_to destroy_user_session_path, method: :delete, class: 'nav-link' do
            = t('sign_out')
      - else
        %li.nav-item
          = link_to new_user_session_path, class: 'nav-link' do
            = t('sign_in')