config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :profiles
  resources :messages
  resources :carpool_passengers do
    member do
      put :approve
      put :decline
    end
  end
  resources :chapters do
    resources :carpools do
      member do
        get :join
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users
      resources :profiles
      resources :messages
      resources :carpool_passengers do
        member do
          put :approve
          put :decline
        end
      end
      resources :chapters do
        resources :carpools do
          member do
            get :join
          end
        end
      end
    end
  end

  get 'author', to: 'resumes#index'

  root to: "main#index"

end

app/models/carpool.rb
# frozen_string_literal: true

class Carpool < ApplicationRecord
  enum frequency: %i[once daily weekly monthly]
  enum weekday: %i[sunday monday tuesday wednesday thursday friday saturday]

  belongs_to :user
  belongs_to :chapter
  has_one :conversation
  has_many :pickup_locations
  has_many :carpool_passengers

  validates :start_location, :end_location, :start_time, :end_time,
            :seats_available, presence: true

  attr_accessor :start_location, :end_location, :start_time, :end_time

  before_validation :load_initial_locations

  scope :latest, -> { order(created_at: :desc) }

  def load_initial_locations
    self.pickup_locations = [
      PickupLocation.new(
        location: start_location,
        arrival_time: start_time,
        sorting_index: 1
      ),
      PickupLocation.new(
        location: end_location,
        arrival_time: end_time,
        sorting_index: 2
      )
    ]
  end

  def start_pickup_location
    @start_pickup_location ||=
      pickup_locations.order(sorting_index: :asc).first
  end

  def end_pickup_location
    @end_pickup_location ||=
      pickup_locations.order(sorting_index: :asc).last
  end

  def add_stop(options = {})
    prior_location = options.delete(:after) || start_pickup_location

    pickup_locations.where('sorting_index > ?', prior_location.sorting_index)
                    .each(&:increment_sorting_index!)

    options[:sorting_index] = prior_location.sorting_index + 1
    pickup_locations.create!(options)
  end

  def stops_count
    pickup_locations.count - 2
  end

  def pickup_at
    start_pickup_location.arrival_time.strftime('%H:%M %p')
  end

  def dropoff_at
    end_pickup_location.arrival_time.strftime('%H:%M %p')
  end

  def remaining_seats
    seats_available - carpool_passengers.approved.count
  end

  def full?
    !remaining_seats.positive?
  end

  def status_for_carpooler(user)
    carpool_passengers.where(user: user).first.status
  end

  def load_conversation
    return conversation if conversation.present?
    Conversation.create!(carpool: self)
  end
end

app/controllers/api/v1/carpools_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class CarpoolsController < Api::V1::BaseController
    end
  end
end

app/controllers/carpools_controller.rb
# frozen_string_literal: true

class CarpoolsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_chapter

  def index
    @carpools = @chapter.carpools.latest
  end

  def new
    @carpool = Carpool.new
  end

  def create
    @carpool = current_user.carpools.new(
      carpool_params.merge(
        chapter: @chapter,
        frequency: carpool_params[:frequency].to_i
      )
    )
    if @carpool.valid?
      @carpool.save
      redirect_to chapter_carpool_path(@chapter, @carpool),
                  notice: 'Carpool successfully created!'
    else
      render :new
    end
  end

  def show
    @carpool = Carpool.find(params[:id])
  end

  def edit
    @carpool = current_user.carpools.find(params[:id])
  end

  def update
    @carpool = current_user.carpools.find(params[:id])
    if @carpool.update_attributes(carpool_params)
      redirect_to chapter_carpool_path(@chapter, @carpool),
                  notice: 'Carpool successfully updated!'
    else
      render :edit
    end
  end

  def join
    @carpool = Carpool.find(params[:id])
    current_user.request_to_join_carpool(@carpool)
    redirect_to chapter_carpool_path(@chapter, @carpool),
                notice: 'Your request was successfully submitted'
  end

  protected

  def find_chapter
    return unless params[:chapter_id].present?
    @chapter = Chapter.friendly.find(params[:chapter_id])
  end

  def carpool_params
    params.require(:carpool).permit(
      :start_location,
      :end_location,
      :start_time,
      :end_time,
      :seats_available,
      :frequency
    )
  end
end

app/views/carpools/_carpool_actions.html.haml
- if owns?(@carpool)
  %h3 Manage
  = card('Update this Carpool',
        link_to('Edit', edit_chapter_carpool_path(@chapter, @carpool), class: 'btn btn-success'))
  = card('Manage Requests', render('passenger_requests', carpool: @carpool))
- elsif joined?(@carpool)
  %h3 Carpool Status
  = card('My Status', @carpool.status_for_carpooler(current_user).titleize)
- else
  %h3 Join
  = card('Join this Carpool', @carpool.full? ? 'No slots available' : link_to('Request to Join', join_chapter_carpool_path(@chapter, @carpool), class: 'btn btn-success'))

app/views/carpools/_carpool_conversation.html.haml
%h3 Conversation
- if approved?(@carpool) || owns?(@carpool)
  = card('Chat', render('carpools/conversation', carpool: @carpool))
- else
  = card('Chat', 'You are not a part of this carpool.')

app/views/carpools/_carpool_details.html.haml
%h3 Carpool Details

= card('User / Driver', link_to(@carpool.user.name, profile_path(@carpool.user)))
= card('Start Location', @carpool.start_pickup_location.location)
= card('End Location', @carpool.end_pickup_location.location)
= card('Frequency', @carpool.frequency.try(:titleize))
= card('Pickup At', @carpool.pickup_at)
= card('Drop off At', @carpool.dropoff_at)
= card('Stops', @carpool.stops_count)
= card('Slots', "#{@carpool.remaining_seats} available")

app/views/carpools/_carpools_table.html.haml
%table.table
  %thead.thead-light
    %tr
      %th.minw-200 Start Location
      %th.minw-200 End Location
      %th Frequency
      %th.minw-150 Time
      %th.minw-100 Drop off
      %th.minw-100 Stops
      %th.minw-150 Slots
  %tbody
    - carpools.each do |carpool|
      %tr
        %td= link_to carpool.start_pickup_location.location, chapter_carpool_path(carpool.chapter, carpool)
        %td= carpool.end_pickup_location.location
        %td= carpool.frequency.try(:titleize)
        %td= carpool.start_pickup_location.pickup_time.strftime("%H:%M %p") rescue ''
        %td= carpool.end_pickup_location.dropoff_time.strftime("%H:%M %p") rescue ''
        %td= carpool.stops_count
        %td= carpool.remaining_seats

app/views/carpools/_conversation.html.haml
.chat-container
  .container-fluid
    .row
      .col-12.messages-container
        - if @carpool.conversation.blank? || @carpool.conversation.messages.blank?
          %p There are no messages
        - else
          - @carpool.conversation.messages.order(created_at: :asc).each do |m|
            .container-fluid.message
              .row.message-header
                .left.col-6
                  = m.user.name
                .right.col-6
                  = m.created_at.strftime("%m/%d/%Y %H:%M %p")
              .row
                .col-12.message-body{class: m.user == current_user ? 'self' : ''}
                  = m.body

  .container-fluid
    .row
      .col-12
        .chat-form-container
          = form_for Message.new(carpool_id: @carpool.id), remote: true do |f|
            = f.hidden_field :carpool_id
            .form-group
              = f.text_area :body, rows: 3, class: 'form-control'
            .form-group
              = f.submit 'Send', class: 'btn btn-success'

app/views/carpools/_form.html.haml
= render 'shared/form_errors', model: @carpool
= form_for @carpool, url: chapter_carpools_path(@chapter, @carpool) do |f|
  .form-group
    = f.label :frequency
    = f.select :frequency, Carpool.frequencies, {prompt: 'Select Frequency'}, class: 'form-control frequency-selector'
  .form-group.carpool-date-select
    = f.label :carpool_date
    = f.text_field :carpool_date, type: 'date', class: 'form-control'
  .form-group.carpool-weekday-select
    = f.label :weekday, 'Day of week'
    = f.select :weekday, Carpool.weekdays, {prompt: 'Select'}, class: 'form-control'
  .form-group.carpool-monthday-select
    = f.label :monthday, 'Day of month'
    = f.select :monthday, (1..31).to_a, {prompt: 'Select'}, class: 'form-control'
  .form-group
    = f.label :seats_available, 'Seats available (ie. 3)'
    = f.text_field :seats_available, class: 'form-control'
  .form-group
    = f.label :start_location
    = f.text_field :start_location, class: 'form-control google-location'
  .form-group
    = f.label :end_location
    = f.text_field :end_location, class: 'form-control google-location'
  .form-group
    = f.label :start_time
    = f.text_field :start_time, class: 'form-control timepicker'
  .form-group
    = f.label :end_time, 'End time (estimated)'
    = f.text_field :end_time, class: 'form-control timepicker'
  .form-group
    = f.submit 'Submit', class: 'btn btn-success'

app/views/carpools/_passenger_requests.html.haml
%table.table
  %thead.thead-light
    %tr
      %th Passenger
      %th Status
      %th Action
  %tbody
    - @carpool.carpool_passengers.each do |p|
      %tr
        %td= link_to p.user.name, profile_path(p.user)
        %td= p.status.titleize
        %td
          - if p.requested?
            = link_to 'Approve', approve_carpool_passenger_path(p), method: :put, class: 'btn btn-success'
            |
            = link_to 'Decline', decline_carpool_passenger_path(p), method: :put, class: 'btn btn-danger'

app/views/carpools/edit.html.haml
.container-fluid
  .row
    .col-md-4
      %h3 Update Carpool
      .card
        .card-body
          = render 'form'
    .col-md-4
      = render 'carpool_actions'
    .col-md-4
      = render 'carpool_conversation'

app/views/carpools/index.html.haml
.container-fluid
  .row
    .col-1
    .col-10
      .container-fluid
        .row
          .col-9
            = render 'chapters/header', chapter: @chapter

            %h3 Carpools
            - if @carpools.any?
              = render 'carpools/carpools_table', carpools: @carpools
            - else
              %p No carpools registered yet

          .col-3
            = render 'users/chapter_members', chapter: @chapter
    .col-1

app/views/carpools/new.html.haml
.container-fluid
  .row
    .col-md-4
    .col-md-4
      %h3 Start a Carpool
      .card
        .card-body
          = render 'form'
    .col-md-4

app/views/carpools/show.html.haml
.container-fluid
  .row
    .col-md-4
      = render 'carpool_details'
    .col-md-4
      = render 'carpool_actions'
    .col-md-4#conversation-module
      = render 'carpool_conversation'