config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :profiles
  resources :messages
  resources :carpool_passengers do
    member do
      put :approve
      put :decline
    end
  end
  resources :chapters do
    resources :carpools do
      member do
        get :join
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users
      resources :profiles
      resources :messages
      resources :carpool_passengers do
        member do
          put :approve
          put :decline
        end
      end
      resources :chapters do
        resources :carpools do
          member do
            get :join
          end
        end
      end
    end
  end

  get 'author', to: 'resumes#index'

  root to: "main#index"

end

app/models/chapter.rb
# frozen_string_literal: true

class Chapter < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :carpools
  belongs_to :user

  geocoded_by :location
  before_validation :load_name
  after_validation :geocode

  def country
    'United States'
  end

  def load_name
    self.name ||= "#{city}, #{state}"
  end

  def location
    "#{city}, #{state}, #{country}"
  end
end

app/controllers/api/v1/chapters_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ChaptersController < Api::V1::BaseController
    end
  end
end

app/controllers/chapters_controller.rb
# frozen_string_literal: true

class ChaptersController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @chapters = Chapter.page(page).per(per_page)
    @nearby = @chapters.near(current_location) if current_location.present?
  end

  def new
    @chapter = Chapter.new
  end

  def show
    @chapter = Chapter.friendly.find(params[:id])
  end

  def create
    @chapter = current_user.chapters.new(chapter_params)
    if @chapter.valid?
      @chapter.save
      redirect_to chapters_path
    else
      render :new
    end
  end

  protected

  def chapter_params
    params.require(:chapter).permit(:name)
  end
end

app/views/chapters/_chapter.html.haml
%li= link_to chapter.name, chapter

app/views/chapters/_form.html.haml
= render 'shared/form_errors', model: @chapter
= form_for @chapter do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :city
    = f.text_field :city, class: 'form-control'
  .form-group
    = f.label :state
    = f.text_field :state, class: 'form-control'
  .form-group
    = f.submit 'Submit', class: 'btn btn-success'

app/views/chapters/_header.html.haml
%h3= chapter.name

%p
  %strong Location:
  %i #{chapter.city}, #{chapter.state}

%p
  = link_to "Offer to Carpooling in #{@chapter.name}", new_chapter_carpool_path(@chapter)

app/views/chapters/_members.html.haml
%h3 Members

app/views/chapters/index.html.haml
- if @nearby.present?
  %h3 Nearby Chapters

  %ul.chapters-container
    = render @nearby

  = paginate @nearby

%h3 All Chapters

%ul.chapters-container
  = render @chapters

= paginate @chapters

app/views/chapters/new.html.haml
.container-fluid
  .row
    .col-md-4
    .col-md-4
      %h3 Start a Chapter
      .card
        .card-body
          = render 'form'
    .col-md-4

app/views/chapters/show.html.haml
.container-fluid
  .row
    .col-1
    .col-10
      .container-fluid
        .row
          .col-9
            = render 'chapters/header', chapter: @chapter

            - if @chapter.carpools.any?
              %h5 Latest Carpools (#{@chapter.carpools.latest.count})
              = render 'carpools/carpools_table', carpools: @chapter.carpools.latest

          .col-3
            = render 'users/chapter_members', chapter: @chapter
    .col-1